version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    reviewers:
      - rudnovd
    target-branch: 'preview'
    open-pull-requests-limit: 10
    labels:
      - dependencies
