name: release

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            Please refer to [CHANGELOG.md](https://github.com/rudnovd/heroes3tools/blob/master/CHANGELOG.md) for details.
