name: tests

on:
  push:
    branches:
      - preview
      - test
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run stylelint
      - run: npm run build
      - run: npm run test
